#!/usr/bin/env python3
"""Read-only checks for scheduled-workload runtime boundaries."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
from email.parser import Parser
import tomllib
from pathlib import Path


ABI_KEYS = ("version", "implementation", "soabi", "cache_tag", "system", "machine")


def _python_info(executable: str) -> dict:
    code = (
        "import json,platform,sys,sysconfig;"
        "print(json.dumps({"
        "'version':f'{sys.version_info.major}.{sys.version_info.minor}',"
        "'implementation':sys.implementation.name,"
        "'soabi':sysconfig.get_config_var('SOABI'),"
        "'cache_tag':sys.implementation.cache_tag,"
        "'system':platform.system(),'machine':platform.machine(),"
        "'stdlib':sorted(sys.stdlib_module_names)}))"
    )
    result = subprocess.run(
        [executable, "-I", "-B", "-c", code],
        text=True, capture_output=True, check=False, timeout=30,
    )
    if result.returncode:
        raise RuntimeError(result.stderr.strip() or "python probe failed")
    return json.loads(result.stdout)


def _normalize(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def _valid_git_oid(value: str) -> bool:
    return bool(re.fullmatch(r"(?:[0-9a-f]{40}|[0-9a-f]{64})", value))


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _parse_lock(path: Path) -> dict[str, str]:
    packages = {}
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        match = re.match(r"^([A-Za-z0-9_.-]+)==([^ ]+)(?: +--hash=sha256:[0-9a-f]{64})+$", line)
        if not match:
            raise ValueError(f"invalid locked requirement: {line}")
        packages[_normalize(match.group(1))] = match.group(2)
    if not packages:
        raise ValueError("empty extension lock")
    return packages


def _installed_packages(root: Path) -> dict[str, str]:
    packages = {}
    for metadata_path in root.glob("*.dist-info/METADATA"):
        metadata = Parser().parsestr(metadata_path.read_text(errors="replace"))
        packages[_normalize(metadata["Name"])] = metadata["Version"]
    return packages


def _file_hashes(root: Path, excluded: Path | None = None) -> dict[str, str]:
    excluded = excluded.resolve() if excluded else None
    return {
        str(path.relative_to(root)): _sha256(path)
        for path in sorted(root.rglob("*"))
        if path.is_file() and path.resolve() != excluded and "__pycache__" not in path.parts
    }


def _bytecode_files(root: Path) -> list[Path]:
    return [
        path for path in root.rglob("*")
        if path.is_file() and (path.suffix in {".pyc", ".pyo"} or "__pycache__" in path.parts)
    ]


def _writable_entries(root: Path) -> list[Path]:
    return [path for path in (root, *root.rglob("*")) if path.lstat().st_mode & 0o222]


def _core_packages(executable: str) -> set[str]:
    code = (
        "import importlib.metadata,json,re;"
        "n=lambda s:re.sub(r\"[-_.]+\",\"-\",s).lower();"
        "print(json.dumps(sorted({n(d.metadata[\"Name\"]) for d in importlib.metadata.distributions() if d.metadata[\"Name\"]})))"
    )
    result = subprocess.run(
        [executable, "-I", "-B", "-c", code],
        text=True, capture_output=True, check=False, timeout=30,
    )
    if result.returncode:
        raise RuntimeError(result.stderr.strip() or "core package probe failed")
    return set(json.loads(result.stdout))


def attest_extension(
    root: Path, lockfile: Path, executable: str, output: Path, source_commit: str,
) -> dict:
    runtime = _python_info(executable)
    locked = _parse_lock(lockfile)
    installed = _installed_packages(root)
    if _bytecode_files(root):
        raise ValueError("extension contains generated bytecode")
    if installed != locked:
        raise ValueError(f"installed packages do not match lock: {installed!r}")
    if not _valid_git_oid(source_commit):
        raise ValueError("source commit must be a lowercase Git object ID")
    contract = {
        "schema_version": 1,
        "source_commit": source_commit,
        "python_abi": {key: runtime[key] for key in ABI_KEYS},
        "lock_sha256": _sha256(lockfile),
        "packages": locked,
        "files": _file_hashes(root, output),
    }
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(contract, indent=2, sort_keys=True) + "\n")
    return contract


def _probe_imports(executable: str, root: Path, modules: list[str]) -> str | None:
    if not modules:
        return None
    code = (
        "import importlib,json,sys;"
        "sys.path.insert(0,sys.argv[1]);"
        "[importlib.import_module(name) for name in json.loads(sys.argv[2])]"
    )
    result = subprocess.run(
        [executable, "-I", "-B", "-c", code, str(root), json.dumps(modules)],
        text=True, capture_output=True, check=False, timeout=30,
    )
    return None if result.returncode == 0 else (result.stderr.strip().splitlines()[-1] or "import failed")


def _source_files(raw_paths: list[str]) -> list[Path]:
    files = []
    for raw in raw_paths:
        path = Path(raw)
        if path.is_file():
            files.append(path)
        elif path.is_dir():
            files.extend(
                candidate for candidate in sorted(path.rglob("*.py"))
                if "__pycache__" not in candidate.parts and ".venv" not in candidate.parts
            )
        else:
            raise FileNotFoundError(path)
    return files


def _script_imports(executable: str, path: Path) -> set[str]:
    code = (
        "import ast,json,pathlib,sys;"
        "source=pathlib.Path(sys.argv[1]).read_text();"
        "compile(source,sys.argv[1],'exec');"
        "t=ast.parse(source,filename=sys.argv[1]);"
        "roots=set();"
        "[roots.update(a.name.split('.')[0] for a in n.names) "
        "if isinstance(n,ast.Import) else roots.add(n.module.split('.')[0]) "
        "for n in ast.walk(t) if isinstance(n,(ast.Import,ast.ImportFrom)) and "
        "(not isinstance(n,ast.ImportFrom) or (n.module and n.level == 0))];"
        "print(json.dumps(sorted(roots)))"
    )
    result = subprocess.run(
        [executable, "-I", "-B", "-c", code, str(path)],
        text=True, capture_output=True, check=False, timeout=30,
    )
    if result.returncode:
        raise RuntimeError(result.stderr.strip() or "script probe failed")
    return set(json.loads(result.stdout))


def check(manifest_path: Path) -> dict:
    manifest = tomllib.loads(manifest_path.read_text())
    checks: list[dict] = []
    ok = manifest.get("schema_version") == 1
    if not ok:
        return {"ok": False, "checks": [{"ok": False, "code": "unsupported_schema"}]}
    sections = (
        "python_runtimes", "python_scripts", "extensions", "containers",
        "commands", "boundaries", "shell_scripts",
    )
    if not any(manifest.get(section) for section in sections):
        checks.append({"ok": False, "code": "empty_manifest"})
        ok = False

    runtimes: dict[str, tuple[str, dict]] = {}
    for item in manifest.get("python_runtimes", []):
        name, executable = item["name"], item["executable"]
        try:
            info = _python_info(executable)
            passed = info["version"] == item["expected"]
            runtimes[name] = (executable, info)
            checks.append({"ok": passed, "code": "python_runtime_ok" if passed else "python_version_mismatch", "name": name})
            ok &= passed
        except Exception as exc:
            checks.append({"ok": False, "code": "python_runtime_error", "name": name, "detail": str(exc)})
            ok = False

    for item in manifest.get("python_scripts", []):
        name, path = item["name"], Path(item["path"])
        runtime = runtimes.get(item["runtime"])
        if runtime is None or not path.is_file():
            checks.append({"ok": False, "code": "python_script_missing", "name": name})
            ok = False
            continue
        executable, info = runtime
        try:
            imports = _script_imports(executable, path)
        except Exception as exc:
            checks.append({"ok": False, "code": "python_script_error", "name": name, "detail": str(exc)})
            ok = False
            continue
        try:
            for source in _source_files(item.get("source_paths", [])):
                imports |= _script_imports(executable, source)
        except Exception as exc:
            checks.append({"ok": False, "code": "python_source_error", "name": name, "detail": str(exc)})
            ok = False
            continue
        allowed = set(info["stdlib"]) | set(item.get("allow_imports", []))
        extra = sorted(imports - allowed) if item.get("stdlib_only", False) else []
        passed = not extra
        check_item = {"ok": passed, "code": "python_script_ok" if passed else "non_stdlib_import", "name": name}
        if extra:
            check_item["detail"] = ",".join(extra)
        checks.append(check_item)
        ok &= passed

    for item in manifest.get("extensions", []):
        name = item["name"]
        root, contract_path, lockfile = Path(item["path"]), Path(item["contract"]), Path(item["lockfile"])
        runtime = runtimes.get(item["runtime"])
        if runtime is None or not root.is_dir() or not contract_path.is_file() or not lockfile.is_file():
            checks.append({"ok": False, "code": "extension_missing", "name": name})
            ok = False
            continue
        try:
            executable, info = runtime
            expected_contract = item.get("contract_sha256", "")
            if not re.fullmatch(r"[0-9a-f]{64}", expected_contract):
                checks.append({"ok": False, "code": "extension_contract_unpinned", "name": name})
                ok = False
                continue
            if _sha256(contract_path) != expected_contract:
                checks.append({"ok": False, "code": "extension_contract_drift", "name": name})
                ok = False
                continue
            contract = json.loads(contract_path.read_text())
            locked = _parse_lock(lockfile)
            installed = _installed_packages(root)
            current_files = _file_hashes(root, contract_path)
            overlap = sorted(set(installed) & _core_packages(executable))
            if contract.get("schema_version") != 1:
                code, detail = "extension_contract_schema", None
            elif not _valid_git_oid(item.get("source_commit", "")) or (
                contract.get("source_commit") != item["source_commit"]
            ):
                code, detail = "extension_source_mismatch", None
            elif _bytecode_files(root):
                code, detail = "extension_unattested_bytecode", None
            elif item.get("read_only", False) and _writable_entries(root):
                code, detail = "extension_writable", None
            elif contract.get("python_abi") != {key: info[key] for key in ABI_KEYS}:
                code, detail = "extension_abi_mismatch", None
            elif contract.get("lock_sha256") != _sha256(lockfile):
                code, detail = "extension_lock_drift", None
            elif contract.get("packages") != locked or installed != locked:
                code, detail = "extension_package_drift", None
            elif contract.get("files") != current_files:
                code, detail = "extension_file_drift", None
            elif overlap:
                code, detail = "extension_core_overlap", ",".join(overlap)
            else:
                import_error = _probe_imports(executable, root, item.get("probe_imports", []))
                code = "extension_import_error" if import_error else "extension_ok"
                detail = import_error or None
            passed = code == "extension_ok"
            check_item = {"ok": passed, "code": code, "name": name}
            if detail:
                check_item["detail"] = detail
            checks.append(check_item)
            ok &= passed
        except Exception as exc:
            checks.append({"ok": False, "code": "extension_error", "name": name, "detail": str(exc)})
            ok = False

    for item in manifest.get("containers", []):
        name = item["name"]
        command = [item["engine"], "inspect", "--type", "container", name]
        if item.get("sudo", False):
            command = ["sudo", "-n", *command]
        try:
            result = subprocess.run(command, text=True, capture_output=True, check=False, timeout=30)
            if result.returncode:
                raise RuntimeError(result.stderr.strip() or "container inspect failed")
            inspected = json.loads(result.stdout)[0]
            if inspected.get("Image") != item["expected_image"]:
                code, passed = "container_image_mismatch", False
            elif inspected.get("State", {}).get("Status") != item["expected_state"]:
                code, passed = "container_state_mismatch", False
            else:
                code, passed = "container_ok", True
            checks.append({"ok": passed, "code": code, "name": name})
            ok &= passed
        except Exception as exc:
            checks.append({"ok": False, "code": "container_unavailable", "name": name, "detail": str(exc)})
            ok = False

    for item in manifest.get("commands", []):
        name, executable = item["name"], Path(item["executable"])
        passed = executable.is_file() and os.access(executable, os.X_OK)
        checks.append({"ok": passed, "code": "command_ok" if passed else "command_missing", "name": name})
        ok &= passed

    for item in manifest.get("boundaries", []):
        name, path, kind = item["name"], Path(item["path"]), item["kind"]
        passed = path.is_dir() if kind == "directory" else path.is_file() if kind == "file" else False
        checks.append({"ok": passed, "code": "boundary_ok" if passed else "boundary_missing", "name": name})
        ok &= passed

    for item in manifest.get("shell_scripts", []):
        name, path = item["name"], Path(item["path"])
        if not path.is_file():
            checks.append({"ok": False, "code": "shell_script_missing", "name": name})
            ok = False
            continue
        try:
            result = subprocess.run(
                [item.get("shell", "/usr/bin/bash"), "-n", str(path)],
                text=True, capture_output=True, check=False, timeout=30,
            )
            passed = result.returncode == 0
            check_item = {"ok": passed, "code": "shell_script_ok" if passed else "shell_syntax_error", "name": name}
            if not passed:
                check_item["detail"] = result.stderr.strip()
        except Exception as exc:
            passed = False
            check_item = {"ok": False, "code": "shell_unavailable", "name": name, "detail": str(exc)}
        checks.append(check_item)
        ok &= passed

    return {"ok": bool(ok), "checks": checks}


def main() -> int:
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="command", required=True)
    check_parser = sub.add_parser("check")
    check_parser.add_argument("manifest", type=Path)
    check_parser.add_argument("--json", action="store_true")
    attest_parser = sub.add_parser("attest-extension")
    attest_parser.add_argument("path", type=Path)
    attest_parser.add_argument("--lock", type=Path, required=True)
    attest_parser.add_argument("--python", required=True)
    attest_parser.add_argument("--output", type=Path, required=True)
    attest_parser.add_argument("--source-commit", required=True)
    args = parser.parse_args()
    if args.command == "attest-extension":
        attest_extension(args.path, args.lock, args.python, args.output, args.source_commit)
        return 0
    report = check(args.manifest)
    if args.json:
        print(json.dumps(report, sort_keys=True))
    else:
        for item in report["checks"]:
            print(("PASS" if item["ok"] else "FAIL"), item["code"], item.get("name", ""))
    return 0 if report["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
